services:
  forward-auth:
    image: ghcr.io/webzaytsev/forward-auth:latest
    container_name: forward-auth
    restart: unless-stopped
    environment:
      AUTH_PASSWORD: ""
      SESSION_SECRET: ""
      AUTH_DOMAIN: "https://auth.example.com"
    networks:
      - caddy
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    mem_limit: 256m
    pids_limit: 256

networks:
  caddy:
    external: true
