version: '3'

services:
  forward-auth:
    build: .
    environment:
      - AUTH_PASSWORD=1234
      - SESSION_SECRET=your-secret-key-32-bytes-minimum
      - AUTH_DOMAIN=http://auth.zaitsv.dev
    ports:
      - "8080:8080"
