name: Publish Docker image to GHCR

on:
  push:
    branches: [ "main" ] # Действие будет запускаться при push в ветку main
    # Вы можете добавить другие триггеры, например, создание релиза:
    # release:
    #   types: [published]

jobs:
  publish-ghcr:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Необходимо для checkout кода
      packages: write # Необходимо для публикации пакетов (Docker-образов) в GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # Этот шаг полезен для сборки multi-platform образов, но не строго обязателен для одного x86_64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Или github.repository_owner
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # Формирует имя образа как ghcr.io/OWNER/REPO_NAME
          # Пример: ghcr.io/webzaytsev/vpn-bot

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Путь к Dockerfile (корень проекта)
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Опционально: кеширование для ускорения сборок
          cache-to: type=gha,mode=max # Опционально: кеширование 